// <auto-generated />
using LordOfLittleComponents.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LordOfLittleComponents.Migrations
{
    [DbContext(typeof(LordOfLittleComponentsContext))]
    [Migration("20200520011242_thirdOne")]
    partial class thirdOne
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LordOfLittleComponents.Models.TemperatureAndHumidity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Humidity");

                    b.Property<string>("Temperature");

                    b.Property<int>("Teste");

                    b.HasKey("Id");

                    b.ToTable("TemperatureAndHumidity");
                });
#pragma warning restore 612, 618
        }
    }
}
